# Generated by Django 6.0.1 on 2026-01-31 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client_company',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='client company'),
        ),
    ]
