# Generated by Django 6.0.1 on 2026-02-01 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_client_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='amount_spent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='spent amount'),
        ),
        migrations.AddField(
            model_name='project',
            name='estimated_duration',
            field=models.IntegerField(default=0, help_text='estimated duration in days', verbose_name='estimated duration'),
        ),
        migrations.AddField(
            model_name='project',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='total amount'),
        ),
    ]
