# Generated by Django 5.2.10 on 2026-02-05 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_attachmentfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachmentfile',
            old_name='file',
            new_name='file_upload',
        ),
    ]
