# Generated by Django 5.2.10 on 2026-02-05 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_remove_attachmentfile_attachments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachmentfile',
            name='name',
        ),
    ]
