# Generated by Django 5.2.10 on 2026-02-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_remove_attachmentfile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachmentfile',
            name='name',
            field=models.CharField(default=1, max_length=150, verbose_name='name'),
            preserve_default=False,
        ),
    ]
