# Generated by Django 6.0.1 on 2026-01-30 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_addr1_alter_profile_addr2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='addr1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='addr2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='bio'),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='location'),
        ),
    ]
