# Generated by Django 6.0.1 on 2026-01-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profile_addr1_remove_profile_addr2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(upload_to='user_profile/', verbose_name='photo'),
        ),
    ]
