# Generated by Django 6.0.1 on 2026-01-31 07:32

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(upload_to=accounts.models.profile_image_location, verbose_name='photo'),
        ),
    ]
