# Generated by Django 5.2.10 on 2026-02-02 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        ('teams', '0003_alter_team_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='teams.team', verbose_name='team'),
            preserve_default=False,
        ),
    ]
