# Generated by Django 5.2.10 on 2026-02-08 06:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_due_date_alter_task_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2026, 2, 8, 6, 14, 1, 670388, tzinfo=datetime.timezone.utc), verbose_name='due date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2026, 2, 8, 6, 14, 39, 868144, tzinfo=datetime.timezone.utc), verbose_name='start date'),
            preserve_default=False,
        ),
    ]
